UI/Areas/Admin/Controllers/LoginController.cs
using BBL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace UI.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        AdminBBL adminBBL = new AdminBBL();
        IsverenBBL isverenBBL = new IsverenBBL();
        KullaniciBBL kullaniciBBL = new KullaniciBBL();

        // GET: Admin/Login
        public ActionResult Index()
        {
            AdminDTO dto = new AdminDTO();

            return View(dto);
        }
        [HttpPost]
        public ActionResult Index(AdminDTO model)
        {
            if (ModelState.IsValid) {

                AdminDTO kullanici = adminBBL.Login(model);
                if (kullanici.ID != 0)
                {
                    FormsAuthentication.SetAuthCookie(kullanici.Email, false);
                    Session["email"] = kullanici.Email;
                    Session["kullaniciid"] = kullanici.ID;
                    Session["ad"] = kullanici.Ad;
                    Session["Soyad"] = kullanici.Soyad;
                    return RedirectToAction("Index","Admin");
                }
                else
                {
                    return View(model);

                }
                }
            else
            {

                return View(model);
            }   

        }
        [HttpGet]
        public ActionResult IsLogin()
        {
            IsverenDTO dto = new IsverenDTO();

            return View(dto);
        }
        [HttpPost]
        public ActionResult IsLogin(IsverenDTO model)
        {
            if (ModelState.IsValid)
            {

                IsverenDTO isveren = isverenBBL.Login(model);
                if (isveren.ID != 0)
                {

                    FormsAuthentication.SetAuthCookie(isveren.Email, false);
                    Session["email"] = isveren.Email;
                    Session["kullaniciid"] = isveren.ID;
                    Session["ad"] = isveren.Ad;
                    Session["Soyad"] = isveren.Soyad;
                    Session["isverenid"] = isveren.ID;
                    return RedirectToAction("Index", "Isveren");
                }
                else
                {
                    return View(model);

                }
            }
            else
            {

                return View(model);
            }

        }
        [AllowAnonymous]
        public JsonResult Register()
        {

            bool rol = adminBBL.RolRegister();
            bool kullanici = adminBBL.Register();
            if (kullanici == true && rol == true)
            {
                return this.Json("Islem basarili", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return this.Json("Islem basarisiz", JsonRequestBehavior.AllowGet);
            }

        }
        [HttpGet]
        public ActionResult KullaniciLogin()
        {
            KullaniciDTO dto = new KullaniciDTO();

            return View(dto);
        }
        [HttpPost]
        public ActionResult KullaniciLogin(KullaniciDTO model)
        {
            if (ModelState.IsValid)
            {

                KullaniciDTO kullanici = kullaniciBBL.KullaniciLogin(model);
                if (kullanici.ID != 0)
                {
                    FormsAuthentication.SetAuthCookie(kullanici.Email, false);
                    Session["email"] = kullanici.Email;
                    Session["kullaniciid"] = kullanici.ID;
                    Session["ad"] = kullanici.Ad;
                    Session["Soyad"] = kullanici.Soyad;
                    return RedirectToAction("Index", "Kullanici");
                }
                else
                {
                    return View(model);

                }
            }
            else
            {

                return View(model);
            }

        }
        [AllowAnonymous]
        public JsonResult KullaniciRegister()
        {

            bool rol = kullaniciBBL.KullaniciRol();
            bool kullanici = kullaniciBBL.KullaniciRegister();
            if (kullanici == true && rol == true)
            {
                return this.Json("Islem basarili", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return this.Json("Islem basarisiz", JsonRequestBehavior.AllowGet);
            }

        }
    }
}

UI/Areas/Admin/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class SiteController : Controller
    {
        // GET: Admin/Site
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Website menu 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link href="~/Areas/Admin/Content/Css/style.css" rel="stylesheet" />

</head>
<body>
    <section class="ftco-section">

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="index.html">Kariyerim.NET</a>
               
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item active"><a href="#" class="nav-link">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Session["email"]</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="@Url.Action("Index", "Login")">Çıkış Yap</a>
                            </div>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Catalog</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Work</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Blog</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END nav -->
            @RenderBody()      
  </section>
  
    
    <script src="~/Areas/Admin/Content/JS/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/main.js"></script>
    <script src="~/Areas/Admin/Content/JS/popper.js"></script>
</body>
</html>

UI/Areas/Admin/Views/Shared/_IsverenLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Website menu 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/Areas/Admin/Content/Css/style.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/Css/isveren.css" rel="stylesheet" />

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">




</head>
<body>
    <section class="ftco-section">

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="index.html">Kariyerim.NET</a>
               
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item active"><a href="@Url.Action("Index", "Isveren")" class="nav-link">Home</a></li>
                        <li class="nav-item"><a href="@Url.Action("IlanOlustur", "Isveren")" class="nav-link">İlan Oluştur</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Work</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Blog</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Contact</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Session["ad"] @Session["soyad"]</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="@Url.Action("LogOut", "Isveren")">Çıkış Yap</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END nav -->
        <div class="container h-100">
            @RenderBody()
        </div>
    </section>


    <script src="~/Areas/Admin/Content/JS/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/main.js"></script>
    <script src="~/Areas/Admin/Content/JS/popper.js"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

UI/Areas/Admin/Views/Shared/_KullaniciLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Website menu 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="~/Areas/Admin/Content/Css/style.css" rel="stylesheet" />

    <link href="~/Areas/Admin/Content/Css/isveren.css" rel="stylesheet" />

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
    <section class="ftco-section">

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Kullanici")">Kariyerim.NET</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item active"><a href="@Url.Action("Index", "Kullanici")" class="nav-link">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@Session["ad"] @Session["Soyad"]</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="@Url.Action("LogOut", "Kullanici")">Çıkış Yap</a>
                               
                            </div>
                        </li>
                        <li class="nav-item"><a href="@Url.Action("IsAra", "Kullanici")" class="nav-link">İş Ara</a></li>
                        <li class="nav-item"><a href="@Url.Action("CvOlustur", "Kullanici")" class="nav-link">Cv Oluştur</a></li>
                        <li class="nav-item"><a href="@Url.Action("Cv", "Kullanici")" class="nav-link">Cv</a></li>
                       
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END nav -->
        @RenderBody()
    </section>


    <script src="~/Areas/Admin/Content/JS/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/main.js"></script>
    <script src="~/Areas/Admin/Content/JS/popper.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

UI/Areas/Admin/Views/Shared/_SiteLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <title>Website menu 03</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <link href="~/Areas/Admin/Content/Css/style.css" rel="stylesheet" />

</head>
<body>
    <section class="ftco-section">

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="index.html">Kariyerim.NET</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item active"><a href="@Url.Action("Index", "Site")" class="nav-link">Home</a></li>
                       
                        <li class="nav-item"><a href="@Url.Action("Index", "Login")"  class="nav-link">Admin Girisi</a></li>
                        <li class="nav-item"><a href="@Url.Action("IsLogin", "Login")" class="nav-link">Isveren Girisi</a></li>
                        <li class="nav-item"><a href="@Url.Action("KullaniciLogin", "Login")" class="nav-link">Kullanici Girisi</a></li>
                    
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END nav -->
            @RenderBody()      
  </section>
  
    
    <script src="~/Areas/Admin/Content/JS/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <script src="~/Areas/Admin/Content/JS/main.js"></script>
    <script src="~/Areas/Admin/Content/JS/popper.js"></script>
</body>
</html>